version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli  --use-feature=2020-resolver
      - aws --version
      - npm install
      - npm run build
      - pipenv run sam package --template-file template.yml --s3-bucket demo.build.nab --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml