version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv lock --clear
      - pipenv install awscli aws-sam-cli
      - npm run build
      - pipenv run sam package --template-file template.yml --s3-bucket demo.build.nab --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml