AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: The Best Video On The World
Parameters:
  EnvironmentName:
    Type: String
    Default: dev
Conditions:
  IsProd:
    Fn::Equals:
    - Ref: EnvironmentName
    - prod
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 300
    Handler: index.handler
    Environment:
      Variables:
        ENV_NAME:
          Ref: EnvironmentName
Resources:
  CreateVideoInfo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://demo.build.nab/f6480a604739c86ab368c82701306859
